### PR TITLE
Backport some NSLayoutConstraint functionality so Mortar can run on iOS7

### PR DESCRIPTION
**Pull request by BrianKenny**
Hi Jason. Love you take on autolayout :)  I'm saddled w/ ios7 support for the foreseeable future.  Fortunately, making Mortar support iOS 7 wasn't terribly difficult. In short, this PS replaces your use of  NSLayoutConstraint's .active .activateConstraints and .deactivateConstraints w/ internal versions.  They just call through on >= 8.0, and on <8.0 they find the correct common superview & use UIView .addConstraint or .removeConstraint instead.

### CODE REVIEW

**Comment by jmfieldman** [comment]
This is fantastic, thank you!  I'm a bit too busy on a workday to soak this in, but I'll do some testing and try to integrate tomorrow afternoon!

**Comment by jmfieldman** [comment]
Do you mind if I add the MIT license to the top of your LayoutConstraint+Mortar.swift file?

**Comment by BrianKenny** [comment]
Sure, go for it.

**Comment by BrianKenny** [comment]
Thanks :)

**Pull request merged**
