### PR TITLE
Set Swift Version support to 4.0 in the podspec file

### PR DESCRIPTION
**Pull request by JoeSzymanski**

### CODE REVIEW

**Comment by jmfieldman** [comment]
Thanks Joe -- this must be a new thing?  It's not linting in travis's xcode9 image; trying over here https://github.com/jmfieldman/Mortar/pull/22 with xcode9.2

**Comment by JoeSzymanski** [comment]
Yes, this was just added in CocoaPods v1.4.0. See http://blog.cocoapods.org/CocoaPods-1.4.0/ (near  the bottom, Title "Swift Version DSL").

The failure makes me think that Travis is using an older version of Cocoapods.

**Comment by jmfieldman** [comment]
Ok -- I think for now .swift_version will still work even though it's deprecated; I'm guessing when Xcode 9.3 is out of beta travis will update it and have cocoapods 1.4 -- remind me and I'll try the PR again!

**Comment by JoeSzymanski** [comment]
From what I can tell, that works for local usage (apparently related to listing), but doesn't appear to work to set the pod's Swift version to 4.0 when being integrated into other projects.

When I tested updating to v1.4.0.1, the pod install still marked Mortar as using Swift 3.2 (matching what we use in our own app) rather than setting it to Swift 4.

I'll have to see if I can find any information about Travis and Cocoapods updates.

**Comment by JoeSzymanski** [comment]
It looks like you can set the cocoa pods version to install separately: https://docs.travis-ci.com/user/common-build-problems/#Newer-version-of-CocoaPods-required

If you require Cocoapods v1.4.0, you should be a able to handle this new field correctly, I think.

**Comment by jmfieldman** [comment]
Closing this (re: https://github.com/jmfieldman/Mortar/pull/22)

**Pull request closed without merging**
